"""The frame audit. Design: docs/design/verify.md."""

from app.verify.audit import audit_frame, describe_frame, run_checks, seed_for
from app.verify.model import (
    Audit,
    Check,
    CheckResult,
    FrameOutcome,
    FrameState,
    Light,
    ObjectCategory,
    ObjectKind,
    Position,
    RenderedFrame,
    Renderer,
    Setting,
    Severity,
    ShotSize,
    Verdict,
)
from app.verify.prompts import DESCRIBE_PROMPT, JUDGE_PROMPT, render_spec
from app.verify.schema import (
    FrameDescription,
    Judgement,
    ObjectCall,
    PersonCall,
    SeenObject,
    SeenPerson,
)

__all__ = [
    "DESCRIBE_PROMPT",
    "JUDGE_PROMPT",
    "Audit",
    "Check",
    "CheckResult",
    "FrameDescription",
    "FrameOutcome",
    "FrameState",
    "Judgement",
    "Light",
    "ObjectCall",
    "ObjectCategory",
    "ObjectKind",
    "PersonCall",
    "Position",
    "RenderedFrame",
    "Renderer",
    "SeenObject",
    "SeenPerson",
    "Setting",
    "Severity",
    "ShotSize",
    "Verdict",
    "audit_frame",
    "describe_frame",
    "render_spec",
    "run_checks",
    "seed_for",
]
